"""Seed vehicle catalog and maintenance templates into the database."""
import sqlite3

DATABASE = 'vehicle_maintenance.db'

VEHICLE_CATALOG = [
    # Toyota
    ('Toyota', 'Corolla',      2013, 2019, 'benzin',  'sedan'),
    ('Toyota', 'Corolla',      2019, None, 'benzin',  'sedan'),
    ('Toyota', 'Corolla',      2019, None, 'hibrit',  'sedan'),
    ('Toyota', 'Yaris',        2011, 2020, 'benzin',  'hatchback'),
    ('Toyota', 'Yaris',        2020, None, 'benzin',  'hatchback'),
    ('Toyota', 'Yaris',        2020, None, 'hibrit',  'hatchback'),
    ('Toyota', 'RAV4',         2013, 2018, 'benzin',  'suv'),
    ('Toyota', 'RAV4',         2018, None, 'benzin',  'suv'),
    ('Toyota', 'RAV4',         2018, None, 'hibrit',  'suv'),
    ('Toyota', 'C-HR',         2016, None, 'benzin',  'suv'),
    ('Toyota', 'C-HR',         2016, None, 'hibrit',  'suv'),
    ('Toyota', 'Auris',        2012, 2019, 'benzin',  'hatchback'),
    ('Toyota', 'Auris',        2012, 2019, 'hibrit',  'hatchback'),
    ('Toyota', 'Hilux',        2015, None, 'dizel',   'pickup'),
    ('Toyota', 'Land Cruiser', 2015, None, 'dizel',   'suv'),
    ('Toyota', 'Camry',        2018, None, 'hibrit',  'sedan'),
    # Volkswagen
    ('Volkswagen', 'Golf',    2013, 2020, 'benzin',  'hatchback'),
    ('Volkswagen', 'Golf',    2013, 2020, 'dizel',   'hatchback'),
    ('Volkswagen', 'Golf',    2020, None, 'benzin',  'hatchback'),
    ('Volkswagen', 'Golf',    2020, None, 'hibrit',  'hatchback'),
    ('Volkswagen', 'Polo',    2014, 2017, 'benzin',  'hatchback'),
    ('Volkswagen', 'Polo',    2017, None, 'benzin',  'hatchback'),
    ('Volkswagen', 'Passat',  2015, None, 'benzin',  'sedan'),
    ('Volkswagen', 'Passat',  2015, None, 'dizel',   'sedan'),
    ('Volkswagen', 'Tiguan',  2017, None, 'benzin',  'suv'),
    ('Volkswagen', 'Tiguan',  2017, None, 'dizel',   'suv'),
    ('Volkswagen', 'T-Roc',   2018, None, 'benzin',  'suv'),
    ('Volkswagen', 'Touareg', 2018, None, 'benzin',  'suv'),
    ('Volkswagen', 'Touareg', 2018, None, 'dizel',   'suv'),
    # Renault
    ('Renault', 'Megane',   2015, 2022, 'benzin',  'hatchback'),
    ('Renault', 'Megane',   2015, 2022, 'dizel',   'hatchback'),
    ('Renault', 'Megane',   2022, None, 'benzin',  'hatchback'),
    ('Renault', 'Megane',   2022, None, 'elektrik','hatchback'),
    ('Renault', 'Clio',     2012, 2019, 'benzin',  'hatchback'),
    ('Renault', 'Clio',     2019, None, 'benzin',  'hatchback'),
    ('Renault', 'Clio',     2019, None, 'hibrit',  'hatchback'),
    ('Renault', 'Fluence',  2012, 2019, 'benzin',  'sedan'),
    ('Renault', 'Fluence',  2012, 2019, 'dizel',   'sedan'),
    ('Renault', 'Kadjar',   2015, 2022, 'benzin',  'suv'),
    ('Renault', 'Kadjar',   2015, 2022, 'dizel',   'suv'),
    ('Renault', 'Duster',   2012, 2018, 'benzin',  'suv'),
    ('Renault', 'Duster',   2018, None, 'benzin',  'suv'),
    ('Renault', 'Duster',   2018, None, 'dizel',   'suv'),
    ('Renault', 'Taliant',  2021, None, 'benzin',  'sedan'),
    ('Renault', 'Arkana',   2021, None, 'hibrit',  'suv'),
    # Ford
    ('Ford', 'Focus',    2014, 2019, 'benzin',  'hatchback'),
    ('Ford', 'Focus',    2014, 2019, 'dizel',   'hatchback'),
    ('Ford', 'Focus',    2019, None, 'benzin',  'hatchback'),
    ('Ford', 'Fiesta',   2013, 2022, 'benzin',  'hatchback'),
    ('Ford', 'Mondeo',   2014, 2022, 'benzin',  'sedan'),
    ('Ford', 'Mondeo',   2014, 2022, 'dizel',   'sedan'),
    ('Ford', 'Kuga',     2013, 2019, 'benzin',  'suv'),
    ('Ford', 'Kuga',     2019, None, 'benzin',  'suv'),
    ('Ford', 'Kuga',     2019, None, 'hibrit',  'suv'),
    ('Ford', 'Puma',     2020, None, 'benzin',  'suv'),
    ('Ford', 'Puma',     2020, None, 'hibrit',  'suv'),
    ('Ford', 'EcoSport', 2014, 2022, 'benzin',  'suv'),
    ('Ford', 'Ranger',   2015, None, 'dizel',   'pickup'),
    # Honda
    ('Honda', 'Civic',  2012, 2016, 'benzin',  'sedan'),
    ('Honda', 'Civic',  2016, 2022, 'benzin',  'sedan'),
    ('Honda', 'Civic',  2022, None, 'benzin',  'sedan'),
    ('Honda', 'CR-V',   2012, 2018, 'benzin',  'suv'),
    ('Honda', 'CR-V',   2018, None, 'benzin',  'suv'),
    ('Honda', 'CR-V',   2018, None, 'hibrit',  'suv'),
    ('Honda', 'HR-V',   2015, 2022, 'benzin',  'suv'),
    ('Honda', 'HR-V',   2022, None, 'hibrit',  'suv'),
    # Hyundai
    ('Hyundai', 'i20',    2012, 2020, 'benzin',  'hatchback'),
    ('Hyundai', 'i20',    2020, None, 'benzin',  'hatchback'),
    ('Hyundai', 'i30',    2012, 2017, 'benzin',  'hatchback'),
    ('Hyundai', 'i30',    2012, 2017, 'dizel',   'hatchback'),
    ('Hyundai', 'i30',    2017, None, 'benzin',  'hatchback'),
    ('Hyundai', 'Tucson', 2016, 2020, 'benzin',  'suv'),
    ('Hyundai', 'Tucson', 2016, 2020, 'dizel',   'suv'),
    ('Hyundai', 'Tucson', 2020, None, 'benzin',  'suv'),
    ('Hyundai', 'Tucson', 2020, None, 'hibrit',  'suv'),
    ('Hyundai', 'Elantra',2016, 2020, 'benzin',  'sedan'),
    ('Hyundai', 'Elantra',2020, None, 'benzin',  'sedan'),
    ('Hyundai', 'Bayon',  2021, None, 'benzin',  'suv'),
    ('Hyundai', 'Kona',   2017, None, 'benzin',  'suv'),
    ('Hyundai', 'Kona',   2020, None, 'elektrik','suv'),
    ('Hyundai', 'IONIQ',  2019, 2022, 'hibrit',  'sedan'),
    ('Hyundai', 'IONIQ 5',2021, None, 'elektrik','suv'),
    # Kia
    ('Kia', 'Sportage', 2016, 2021, 'benzin',  'suv'),
    ('Kia', 'Sportage', 2016, 2021, 'dizel',   'suv'),
    ('Kia', 'Sportage', 2021, None, 'benzin',  'suv'),
    ('Kia', 'Sportage', 2021, None, 'hibrit',  'suv'),
    ('Kia', 'Ceed',     2012, 2018, 'benzin',  'hatchback'),
    ('Kia', 'Ceed',     2018, None, 'benzin',  'hatchback'),
    ('Kia', 'Stinger',  2017, None, 'benzin',  'sedan'),
    ('Kia', 'Sorento',  2016, 2020, 'dizel',   'suv'),
    ('Kia', 'Sorento',  2020, None, 'hibrit',  'suv'),
    ('Kia', 'Picanto',  2011, 2017, 'benzin',  'hatchback'),
    ('Kia', 'Picanto',  2017, None, 'benzin',  'hatchback'),
    ('Kia', 'EV6',      2021, None, 'elektrik','suv'),
    # Dacia
    ('Dacia', 'Sandero', 2012, 2020, 'benzin',  'hatchback'),
    ('Dacia', 'Sandero', 2012, 2020, 'lpg',     'hatchback'),
    ('Dacia', 'Sandero', 2020, None, 'benzin',  'hatchback'),
    ('Dacia', 'Logan',   2012, 2020, 'benzin',  'sedan'),
    ('Dacia', 'Logan',   2020, None, 'benzin',  'sedan'),
    ('Dacia', 'Duster',  2012, 2018, 'benzin',  'suv'),
    ('Dacia', 'Duster',  2012, 2018, 'dizel',   'suv'),
    ('Dacia', 'Duster',  2018, None, 'benzin',  'suv'),
    ('Dacia', 'Duster',  2018, None, 'dizel',   'suv'),
    ('Dacia', 'Spring',  2021, None, 'elektrik','hatchback'),
    # Skoda
    ('Skoda', 'Octavia', 2013, 2020, 'benzin',  'sedan'),
    ('Skoda', 'Octavia', 2013, 2020, 'dizel',   'sedan'),
    ('Skoda', 'Octavia', 2020, None, 'benzin',  'sedan'),
    ('Skoda', 'Octavia', 2020, None, 'hibrit',  'sedan'),
    ('Skoda', 'Fabia',   2015, 2021, 'benzin',  'hatchback'),
    ('Skoda', 'Fabia',   2021, None, 'benzin',  'hatchback'),
    ('Skoda', 'Karoq',   2017, None, 'benzin',  'suv'),
    ('Skoda', 'Karoq',   2017, None, 'dizel',   'suv'),
    ('Skoda', 'Superb',  2015, None, 'benzin',  'sedan'),
    ('Skoda', 'Superb',  2015, None, 'dizel',   'sedan'),
    ('Skoda', 'Kodiaq',  2017, None, 'benzin',  'suv'),
    ('Skoda', 'Kodiaq',  2017, None, 'dizel',   'suv'),
    # BMW
    ('BMW', '1 Serisi', 2012, 2019, 'benzin',  'hatchback'),
    ('BMW', '1 Serisi', 2019, None, 'benzin',  'hatchback'),
    ('BMW', '3 Serisi', 2012, 2018, 'benzin',  'sedan'),
    ('BMW', '3 Serisi', 2012, 2018, 'dizel',   'sedan'),
    ('BMW', '3 Serisi', 2018, None, 'benzin',  'sedan'),
    ('BMW', '3 Serisi', 2018, None, 'dizel',   'sedan'),
    ('BMW', '5 Serisi', 2013, 2017, 'benzin',  'sedan'),
    ('BMW', '5 Serisi', 2013, 2017, 'dizel',   'sedan'),
    ('BMW', '5 Serisi', 2017, None, 'benzin',  'sedan'),
    ('BMW', '5 Serisi', 2017, None, 'dizel',   'sedan'),
    ('BMW', 'X1',       2016, None, 'benzin',  'suv'),
    ('BMW', 'X1',       2016, None, 'dizel',   'suv'),
    ('BMW', 'X3',       2017, None, 'benzin',  'suv'),
    ('BMW', 'X3',       2017, None, 'dizel',   'suv'),
    ('BMW', 'X5',       2018, None, 'benzin',  'suv'),
    ('BMW', 'X5',       2018, None, 'dizel',   'suv'),
    # Mercedes-Benz
    ('Mercedes-Benz', 'A Serisi', 2013, 2018, 'benzin',  'hatchback'),
    ('Mercedes-Benz', 'A Serisi', 2018, None, 'benzin',  'hatchback'),
    ('Mercedes-Benz', 'C Serisi', 2014, 2021, 'benzin',  'sedan'),
    ('Mercedes-Benz', 'C Serisi', 2014, 2021, 'dizel',   'sedan'),
    ('Mercedes-Benz', 'C Serisi', 2021, None, 'benzin',  'sedan'),
    ('Mercedes-Benz', 'E Serisi', 2016, None, 'benzin',  'sedan'),
    ('Mercedes-Benz', 'E Serisi', 2016, None, 'dizel',   'sedan'),
    ('Mercedes-Benz', 'GLC',      2015, None, 'benzin',  'suv'),
    ('Mercedes-Benz', 'GLC',      2015, None, 'dizel',   'suv'),
    ('Mercedes-Benz', 'CLA',      2014, None, 'benzin',  'sedan'),
    ('Mercedes-Benz', 'GLA',      2014, None, 'benzin',  'suv'),
    # Fiat
    ('Fiat', 'Egea',  2016, None, 'benzin',  'sedan'),
    ('Fiat', 'Egea',  2016, None, 'dizel',   'sedan'),
    ('Fiat', 'Tipo',  2016, None, 'benzin',  'hatchback'),
    ('Fiat', 'Tipo',  2016, None, 'dizel',   'hatchback'),
    ('Fiat', '500',   2008, None, 'benzin',  'hatchback'),
    ('Fiat', '500',   2020, None, 'elektrik','hatchback'),
    # Opel
    ('Opel', 'Corsa',     2015, 2019, 'benzin',  'hatchback'),
    ('Opel', 'Corsa',     2019, None, 'benzin',  'hatchback'),
    ('Opel', 'Corsa',     2019, None, 'elektrik','hatchback'),
    ('Opel', 'Astra',     2016, 2021, 'benzin',  'hatchback'),
    ('Opel', 'Astra',     2016, 2021, 'dizel',   'hatchback'),
    ('Opel', 'Astra',     2021, None, 'benzin',  'hatchback'),
    ('Opel', 'Mokka',     2021, None, 'benzin',  'suv'),
    ('Opel', 'Mokka',     2021, None, 'elektrik','suv'),
    ('Opel', 'Crossland', 2017, None, 'benzin',  'suv'),
    ('Opel', 'Grandland', 2017, None, 'benzin',  'suv'),
    ('Opel', 'Grandland', 2017, None, 'hibrit',  'suv'),
    # Peugeot
    ('Peugeot', '208',   2013, 2019, 'benzin',  'hatchback'),
    ('Peugeot', '208',   2019, None, 'benzin',  'hatchback'),
    ('Peugeot', '208',   2019, None, 'elektrik','hatchback'),
    ('Peugeot', '308',   2013, 2021, 'benzin',  'hatchback'),
    ('Peugeot', '308',   2013, 2021, 'dizel',   'hatchback'),
    ('Peugeot', '308',   2021, None, 'benzin',  'hatchback'),
    ('Peugeot', '3008',  2017, None, 'benzin',  'suv'),
    ('Peugeot', '3008',  2017, None, 'dizel',   'suv'),
    ('Peugeot', '3008',  2017, None, 'hibrit',  'suv'),
    ('Peugeot', '5008',  2017, None, 'benzin',  'suv'),
    ('Peugeot', '5008',  2017, None, 'dizel',   'suv'),
    # Seat
    ('Seat', 'Leon',  2013, 2020, 'benzin',  'hatchback'),
    ('Seat', 'Leon',  2013, 2020, 'dizel',   'hatchback'),
    ('Seat', 'Leon',  2020, None, 'benzin',  'hatchback'),
    ('Seat', 'Leon',  2020, None, 'hibrit',  'hatchback'),
    ('Seat', 'Ibiza', 2017, None, 'benzin',  'hatchback'),
    ('Seat', 'Ateca', 2016, None, 'benzin',  'suv'),
    ('Seat', 'Ateca', 2016, None, 'dizel',   'suv'),
    ('Seat', 'Arona', 2017, None, 'benzin',  'suv'),
    # Nissan
    ('Nissan', 'Qashqai', 2014, 2021, 'benzin',  'suv'),
    ('Nissan', 'Qashqai', 2021, None, 'benzin',  'suv'),
    ('Nissan', 'Qashqai', 2021, None, 'hibrit',  'suv'),
    ('Nissan', 'Juke',    2014, 2020, 'benzin',  'suv'),
    ('Nissan', 'Juke',    2020, None, 'benzin',  'suv'),
    ('Nissan', 'Leaf',    2018, None, 'elektrik','hatchback'),
    ('Nissan', 'X-Trail', 2014, None, 'benzin',  'suv'),
    ('Nissan', 'X-Trail', 2014, None, 'dizel',   'suv'),
    # Mazda
    ('Mazda', 'Mazda3', 2014, 2019, 'benzin',  'sedan'),
    ('Mazda', 'Mazda3', 2019, None, 'benzin',  'sedan'),
    ('Mazda', 'Mazda6', 2013, 2021, 'benzin',  'sedan'),
    ('Mazda', 'CX-5',   2017, None, 'benzin',  'suv'),
    ('Mazda', 'CX-5',   2017, None, 'dizel',   'suv'),
    ('Mazda', 'CX-30',  2020, None, 'benzin',  'suv'),
    ('Mazda', 'CX-30',  2020, None, 'hibrit',  'suv'),
    # Mitsubishi
    ('Mitsubishi', 'Eclipse Cross', 2018, None, 'benzin',  'suv'),
    ('Mitsubishi', 'Outlander',     2013, None, 'benzin',  'suv'),
    ('Mitsubishi', 'Outlander',     2013, None, 'hibrit',  'suv'),
    ('Mitsubishi', 'L200',          2015, None, 'dizel',   'pickup'),
    # Subaru
    ('Subaru', 'Outback',  2015, 2021, 'benzin',  'suv'),
    ('Subaru', 'Outback',  2021, None, 'benzin',  'suv'),
    ('Subaru', 'Forester', 2013, 2019, 'benzin',  'suv'),
    ('Subaru', 'Forester', 2019, None, 'benzin',  'suv'),
    ('Subaru', 'XV',       2017, None, 'benzin',  'suv'),
    # Volvo
    ('Volvo', 'XC60', 2018, None, 'benzin',  'suv'),
    ('Volvo', 'XC60', 2018, None, 'dizel',   'suv'),
    ('Volvo', 'XC60', 2018, None, 'hibrit',  'suv'),
    ('Volvo', 'S60',  2019, None, 'benzin',  'sedan'),
    ('Volvo', 'XC40', 2018, None, 'benzin',  'suv'),
    ('Volvo', 'XC40', 2020, None, 'elektrik','suv'),
    # Audi
    ('Audi', 'A3', 2014, 2020, 'benzin',  'hatchback'),
    ('Audi', 'A3', 2014, 2020, 'dizel',   'hatchback'),
    ('Audi', 'A3', 2020, None, 'benzin',  'hatchback'),
    ('Audi', 'A4', 2016, None, 'benzin',  'sedan'),
    ('Audi', 'A4', 2016, None, 'dizel',   'sedan'),
    ('Audi', 'Q3', 2015, None, 'benzin',  'suv'),
    ('Audi', 'Q5', 2017, None, 'benzin',  'suv'),
    ('Audi', 'Q5', 2017, None, 'dizel',   'suv'),
    # Suzuki
    ('Suzuki', 'Swift',   2011, 2018, 'benzin',  'hatchback'),
    ('Suzuki', 'Swift',   2018, None, 'benzin',  'hatchback'),
    ('Suzuki', 'Vitara',  2015, None, 'benzin',  'suv'),
    ('Suzuki', 'SX4',     2014, None, 'benzin',  'suv'),
    ('Suzuki', 'Jimny',   2018, None, 'benzin',  'suv'),
    # Jeep
    ('Jeep', 'Renegade', 2015, None, 'benzin',  'suv'),
    ('Jeep', 'Compass',  2017, None, 'benzin',  'suv'),
    ('Jeep', 'Compass',  2017, None, 'hibrit',  'suv'),
    # Citroen
    ('Citroen', 'C3',       2016, None, 'benzin',  'hatchback'),
    ('Citroen', 'C5 X',     2021, None, 'benzin',  'suv'),
    ('Citroen', 'C5 X',     2021, None, 'hibrit',  'suv'),
    ('Citroen', 'Berlingo', 2018, None, 'benzin',  'van'),
    # Alfa Romeo
    ('Alfa Romeo', 'Giulia',  2016, None, 'benzin',  'sedan'),
    ('Alfa Romeo', 'Stelvio', 2017, None, 'benzin',  'suv'),
    # Porsche
    ('Porsche', 'Cayenne', 2018, None, 'benzin',  'suv'),
    ('Porsche', 'Macan',   2014, None, 'benzin',  'suv'),
    ('Porsche', 'Taycan',  2020, None, 'elektrik','sedan'),
    # Toyota additional
    ('Toyota', 'Prius',         2016, None, 'hibrit',  'sedan'),
    ('Toyota', 'Corolla Cross', 2022, None, 'benzin',  'suv'),
    ('Toyota', 'Corolla Cross', 2022, None, 'hibrit',  'suv'),
    ('Toyota', 'bZ4X',          2022, None, 'elektrik','suv'),
    # Volkswagen additional
    ('Volkswagen', 'ID.3',  2020, None, 'elektrik','hatchback'),
    ('Volkswagen', 'ID.4',  2021, None, 'elektrik','suv'),
    ('Volkswagen', 'Caddy', 2021, None, 'benzin',  'van'),
    # Renault additional
    ('Renault', 'Symbol',   2016, None, 'benzin',  'sedan'),
    ('Renault', 'Talisman', 2016, None, 'benzin',  'sedan'),
    ('Renault', 'Talisman', 2016, None, 'dizel',   'sedan'),
    ('Renault', 'Austral',  2022, None, 'hibrit',  'suv'),
    ('Renault', 'Zoe',      2019, None, 'elektrik','hatchback'),
    # Ford additional
    ('Ford', 'Tourneo Courier', 2015, None, 'dizel',  'van'),
    ('Ford', 'Tourneo Courier', 2015, None, 'benzin', 'van'),
    # Honda additional
    ('Honda', 'Jazz', 2020, None, 'hibrit', 'hatchback'),
    # Hyundai additional
    ('Hyundai', 'i10',     2020, None, 'benzin',  'hatchback'),
    ('Hyundai', 'IONIQ 6', 2022, None, 'elektrik','sedan'),
    # Kia additional
    ('Kia', 'Rio', 2017, None, 'benzin',  'hatchback'),
    ('Kia', 'EV9', 2023, None, 'elektrik','suv'),
    # Dacia additional
    ('Dacia', 'Jogger', 2022, None, 'benzin', 'van'),
    # Skoda additional
    ('Skoda', 'Enyaq', 2021, None, 'elektrik','suv'),
    ('Skoda', 'Scala', 2019, None, 'benzin',  'hatchback'),
    # BMW additional
    ('BMW', '2 Serisi', 2021, None, 'benzin',  'hatchback'),
    ('BMW', 'i4',       2021, None, 'elektrik','sedan'),
    ('BMW', 'iX3',      2020, None, 'elektrik','suv'),
    # Mercedes additional
    ('Mercedes-Benz', 'GLE', 2019, None, 'benzin', 'suv'),
    ('Mercedes-Benz', 'GLE', 2019, None, 'dizel',  'suv'),
    ('Mercedes-Benz', 'GLB', 2019, None, 'benzin', 'suv'),
    ('Mercedes-Benz', 'EQA', 2021, None, 'elektrik','suv'),
    # Fiat additional
    ('Fiat', 'Panda', 2013, None, 'benzin', 'hatchback'),
    ('Fiat', 'Doblo', 2021, None, 'benzin', 'van'),
    ('Fiat', 'Doblo', 2021, None, 'dizel',  'van'),
    # Opel additional
    ('Opel', 'Combo', 2018, None, 'benzin', 'van'),
    ('Opel', 'Combo', 2018, None, 'dizel',  'van'),
    # Citroen additional
    ('Citroen', 'C4', 2020, None, 'benzin',  'hatchback'),
    ('Citroen', 'C4', 2020, None, 'elektrik','hatchback'),
    # Peugeot additional
    ('Peugeot', '2008', 2020, None, 'benzin',  'suv'),
    ('Peugeot', '2008', 2020, None, 'elektrik','suv'),
    # Seat additional
    ('Seat', 'Tarraco', 2018, None, 'benzin', 'suv'),
    ('Seat', 'Tarraco', 2018, None, 'dizel',  'suv'),
    # Audi additional
    ('Audi', 'A6', 2018, None, 'benzin', 'sedan'),
    ('Audi', 'A6', 2018, None, 'dizel',  'sedan'),
    ('Audi', 'Q7', 2015, None, 'benzin', 'suv'),
    ('Audi', 'Q7', 2015, None, 'dizel',  'suv'),
    # Tesla (new brand)
    ('Tesla', 'Model 3', 2019, None, 'elektrik','sedan'),
    ('Tesla', 'Model Y', 2021, None, 'elektrik','suv'),
    # Cupra (new brand)
    ('Cupra', 'Formentor', 2021, None, 'benzin',  'suv'),
    ('Cupra', 'Formentor', 2021, None, 'hibrit',  'suv'),
    ('Cupra', 'Born',      2022, None, 'elektrik','hatchback'),
]

ENGINE_VARIANTS = [
    # Toyota
    ('Toyota', 'Corolla', '1.2T benzin', 'benzin'),
    ('Toyota', 'Corolla', '1.6 benzin', 'benzin'),
    ('Toyota', 'Corolla', '1.8 Hibrit', 'hibrit'),
    ('Toyota', 'Yaris', '1.0 benzin', 'benzin'),
    ('Toyota', 'Yaris', '1.5 benzin', 'benzin'),
    ('Toyota', 'Yaris', '1.5 Hibrit', 'hibrit'),
    ('Toyota', 'RAV4', '2.0 benzin', 'benzin'),
    ('Toyota', 'RAV4', '2.5 Hibrit', 'hibrit'),
    ('Toyota', 'C-HR', '1.2T benzin', 'benzin'),
    ('Toyota', 'C-HR', '2.0 Hibrit', 'hibrit'),
    ('Toyota', 'Auris', '1.33 benzin', 'benzin'),
    ('Toyota', 'Auris', '1.6 benzin', 'benzin'),
    ('Toyota', 'Auris', '1.8 Hibrit', 'hibrit'),
    ('Toyota', 'Hilux', '2.4 D-4D dizel', 'dizel'),
    ('Toyota', 'Hilux', '2.8 D-4D dizel', 'dizel'),
    ('Toyota', 'Land Cruiser', '2.8 D-4D dizel', 'dizel'),
    ('Toyota', 'Land Cruiser', '3.0 D-4D dizel', 'dizel'),
    ('Toyota', 'Camry', '2.5 Hibrit', 'hibrit'),
    # Volkswagen
    ('Volkswagen', 'Golf', '1.0 TSI benzin', 'benzin'),
    ('Volkswagen', 'Golf', '1.4 TSI benzin', 'benzin'),
    ('Volkswagen', 'Golf', '1.5 TSI benzin', 'benzin'),
    ('Volkswagen', 'Golf', '2.0 TSI benzin', 'benzin'),
    ('Volkswagen', 'Golf', '1.6 TDI dizel', 'dizel'),
    ('Volkswagen', 'Golf', '2.0 TDI dizel', 'dizel'),
    ('Volkswagen', 'Golf', '1.4 GTE hibrit', 'hibrit'),
    ('Volkswagen', 'Polo', '1.0 MPI benzin', 'benzin'),
    ('Volkswagen', 'Polo', '1.0 TSI benzin', 'benzin'),
    ('Volkswagen', 'Polo', '1.5 TSI benzin', 'benzin'),
    ('Volkswagen', 'Passat', '1.5 TSI benzin', 'benzin'),
    ('Volkswagen', 'Passat', '2.0 TSI benzin', 'benzin'),
    ('Volkswagen', 'Passat', '1.6 TDI dizel', 'dizel'),
    ('Volkswagen', 'Passat', '2.0 TDI dizel', 'dizel'),
    ('Volkswagen', 'Tiguan', '1.4 TSI benzin', 'benzin'),
    ('Volkswagen', 'Tiguan', '1.5 TSI benzin', 'benzin'),
    ('Volkswagen', 'Tiguan', '2.0 TSI benzin', 'benzin'),
    ('Volkswagen', 'Tiguan', '2.0 TDI dizel', 'dizel'),
    ('Volkswagen', 'T-Roc', '1.0 TSI benzin', 'benzin'),
    ('Volkswagen', 'T-Roc', '1.5 TSI benzin', 'benzin'),
    ('Volkswagen', 'T-Roc', '2.0 TDI dizel', 'dizel'),
    ('Volkswagen', 'Touareg', '3.0 V6 TSI benzin', 'benzin'),
    ('Volkswagen', 'Touareg', '3.0 TDI dizel', 'dizel'),
    # Renault
    ('Renault', 'Megane', '1.3 TCe benzin', 'benzin'),
    ('Renault', 'Megane', '1.6 benzin', 'benzin'),
    ('Renault', 'Megane', '1.5 dCi dizel', 'dizel'),
    ('Renault', 'Clio', '1.0 SCe benzin', 'benzin'),
    ('Renault', 'Clio', '1.0 TCe benzin', 'benzin'),
    ('Renault', 'Clio', '1.3 TCe benzin', 'benzin'),
    ('Renault', 'Clio', '1.5 dCi dizel', 'dizel'),
    ('Renault', 'Clio', '1.6 E-Tech hibrit', 'hibrit'),
    ('Renault', 'Fluence', '1.6 benzin', 'benzin'),
    ('Renault', 'Fluence', '2.0 benzin', 'benzin'),
    ('Renault', 'Fluence', '1.5 dCi dizel', 'dizel'),
    ('Renault', 'Kadjar', '1.3 TCe benzin', 'benzin'),
    ('Renault', 'Kadjar', '1.5 dCi dizel', 'dizel'),
    ('Renault', 'Kadjar', '1.6 dCi dizel', 'dizel'),
    ('Renault', 'Duster', '1.0 TCe benzin', 'benzin'),
    ('Renault', 'Duster', '1.3 TCe benzin', 'benzin'),
    ('Renault', 'Duster', '1.6 benzin', 'benzin'),
    ('Renault', 'Duster', '1.5 dCi dizel', 'dizel'),
    ('Renault', 'Taliant', '1.0 TCe benzin', 'benzin'),
    ('Renault', 'Arkana', '1.3 TCe hibrit', 'hibrit'),
    # Ford
    ('Ford', 'Focus', '1.0 EcoBoost benzin', 'benzin'),
    ('Ford', 'Focus', '1.5 EcoBoost benzin', 'benzin'),
    ('Ford', 'Focus', '2.0 EcoBlue dizel', 'dizel'),
    ('Ford', 'Fiesta', '1.0 EcoBoost benzin', 'benzin'),
    ('Ford', 'Fiesta', '1.1 benzin', 'benzin'),
    ('Ford', 'Fiesta', '1.25 benzin', 'benzin'),
    ('Ford', 'Fiesta', '1.4 benzin', 'benzin'),
    ('Ford', 'Fiesta', '1.6 benzin', 'benzin'),
    ('Ford', 'Fiesta', '1.4 TDCi dizel', 'dizel'),
    ('Ford', 'Fiesta', '1.5 TDCi dizel', 'dizel'),
    ('Ford', 'Mondeo', '1.5 EcoBoost benzin', 'benzin'),
    ('Ford', 'Mondeo', '2.0 EcoBoost benzin', 'benzin'),
    ('Ford', 'Mondeo', '2.0 TDCi dizel', 'dizel'),
    ('Ford', 'Kuga', '1.5 EcoBoost benzin', 'benzin'),
    ('Ford', 'Kuga', '2.0 EcoBlue dizel', 'dizel'),
    ('Ford', 'Kuga', '2.5 Duratec Hibrit', 'hibrit'),
    ('Ford', 'Puma', '1.0 EcoBoost benzin', 'benzin'),
    ('Ford', 'Puma', '1.0 mHEV hibrit', 'hibrit'),
    ('Ford', 'EcoSport', '1.0 EcoBoost benzin', 'benzin'),
    ('Ford', 'EcoSport', '1.5 TDCi dizel', 'dizel'),
    ('Ford', 'Ranger', '2.0 EcoBlue dizel', 'dizel'),
    ('Ford', 'Ranger', '3.2 TDCi dizel', 'dizel'),
    # Honda
    ('Honda', 'Civic', '1.0 i-VTEC benzin', 'benzin'),
    ('Honda', 'Civic', '1.5 VTEC benzin', 'benzin'),
    ('Honda', 'Civic', '2.0 i-VTEC benzin', 'benzin'),
    ('Honda', 'CR-V', '1.5 VTEC benzin', 'benzin'),
    ('Honda', 'CR-V', '2.0 i-MMD hibrit', 'hibrit'),
    ('Honda', 'HR-V', '1.5 i-VTEC benzin', 'benzin'),
    ('Honda', 'HR-V', '1.5 e:HEV hibrit', 'hibrit'),
    # Hyundai
    ('Hyundai', 'i20', '1.0 T-GDI benzin', 'benzin'),
    ('Hyundai', 'i20', '1.2 MPI benzin', 'benzin'),
    ('Hyundai', 'i30', '1.0 T-GDI benzin', 'benzin'),
    ('Hyundai', 'i30', '1.4 T-GDI benzin', 'benzin'),
    ('Hyundai', 'i30', '1.5 T-GDI benzin', 'benzin'),
    ('Hyundai', 'i30', '2.0 benzin', 'benzin'),
    ('Hyundai', 'i30', '1.6 CRDi dizel', 'dizel'),
    ('Hyundai', 'Tucson', '1.6 T-GDI benzin', 'benzin'),
    ('Hyundai', 'Tucson', '2.0 MPi benzin', 'benzin'),
    ('Hyundai', 'Tucson', '1.6 CRDi dizel', 'dizel'),
    ('Hyundai', 'Tucson', '1.6 HEV hibrit', 'hibrit'),
    ('Hyundai', 'Elantra', '1.6 MPI benzin', 'benzin'),
    ('Hyundai', 'Elantra', '2.0 MPI benzin', 'benzin'),
    ('Hyundai', 'Bayon', '1.0 T-GDI benzin', 'benzin'),
    ('Hyundai', 'Kona', '1.0 T-GDI benzin', 'benzin'),
    ('Hyundai', 'Kona', '2.0 MPI benzin', 'benzin'),
    ('Hyundai', 'Kona', '64 kWh elektrik', 'elektrik'),
    ('Hyundai', 'IONIQ', '1.6 GDI hibrit', 'hibrit'),
    ('Hyundai', 'IONIQ 5', '58 kWh elektrik', 'elektrik'),
    ('Hyundai', 'IONIQ 5', '77.4 kWh elektrik', 'elektrik'),
    # Kia
    ('Kia', 'Sportage', '1.6 T-GDI benzin', 'benzin'),
    ('Kia', 'Sportage', '2.0 MPI benzin', 'benzin'),
    ('Kia', 'Sportage', '1.6 CRDi dizel', 'dizel'),
    ('Kia', 'Sportage', '2.0 CRDi dizel', 'dizel'),
    ('Kia', 'Sportage', '1.6 HEV hibrit', 'hibrit'),
    ('Kia', 'Ceed', '1.0 T-GDI benzin', 'benzin'),
    ('Kia', 'Ceed', '1.4 T-GDI benzin', 'benzin'),
    ('Kia', 'Ceed', '1.5 T-GDI benzin', 'benzin'),
    ('Kia', 'Stinger', '2.5 T-GDI benzin', 'benzin'),
    ('Kia', 'Stinger', '3.3 T-GDI benzin', 'benzin'),
    ('Kia', 'Sorento', '2.2 CRDi dizel', 'dizel'),
    ('Kia', 'Sorento', '1.6 T-GDI HEV hibrit', 'hibrit'),
    ('Kia', 'Picanto', '1.0 MPI benzin', 'benzin'),
    ('Kia', 'Picanto', '1.0 T-GDI benzin', 'benzin'),
    ('Kia', 'Picanto', '1.2 MPI benzin', 'benzin'),
    ('Kia', 'EV6', '58 kWh elektrik', 'elektrik'),
    ('Kia', 'EV6', '77.4 kWh elektrik', 'elektrik'),
    # Dacia
    ('Dacia', 'Sandero', '1.0 SCe benzin', 'benzin'),
    ('Dacia', 'Sandero', '1.0 TCe benzin', 'benzin'),
    ('Dacia', 'Sandero', '1.6 MPI benzin', 'benzin'),
    ('Dacia', 'Sandero', '1.6 MPI LPG', 'lpg'),
    ('Dacia', 'Logan', '1.0 SCe benzin', 'benzin'),
    ('Dacia', 'Logan', '1.6 MPI benzin', 'benzin'),
    ('Dacia', 'Duster', '1.0 TCe benzin', 'benzin'),
    ('Dacia', 'Duster', '1.3 TCe benzin', 'benzin'),
    ('Dacia', 'Duster', '1.6 SCe benzin', 'benzin'),
    ('Dacia', 'Duster', '1.5 dCi dizel', 'dizel'),
    ('Dacia', 'Spring', '26.8 kWh elektrik', 'elektrik'),
    # Skoda
    ('Skoda', 'Octavia', '1.0 TSI benzin', 'benzin'),
    ('Skoda', 'Octavia', '1.4 TSI benzin', 'benzin'),
    ('Skoda', 'Octavia', '1.5 TSI benzin', 'benzin'),
    ('Skoda', 'Octavia', '2.0 TSI benzin', 'benzin'),
    ('Skoda', 'Octavia', '1.6 TDI dizel', 'dizel'),
    ('Skoda', 'Octavia', '2.0 TDI dizel', 'dizel'),
    ('Skoda', 'Octavia', '1.4 TSI iV hibrit', 'hibrit'),
    ('Skoda', 'Fabia', '1.0 MPI benzin', 'benzin'),
    ('Skoda', 'Fabia', '1.0 TSI benzin', 'benzin'),
    ('Skoda', 'Fabia', '1.5 TSI benzin', 'benzin'),
    ('Skoda', 'Karoq', '1.0 TSI benzin', 'benzin'),
    ('Skoda', 'Karoq', '1.5 TSI benzin', 'benzin'),
    ('Skoda', 'Karoq', '2.0 TDI dizel', 'dizel'),
    ('Skoda', 'Superb', '1.5 TSI benzin', 'benzin'),
    ('Skoda', 'Superb', '2.0 TSI benzin', 'benzin'),
    ('Skoda', 'Superb', '2.0 TDI dizel', 'dizel'),
    ('Skoda', 'Kodiaq', '1.5 TSI benzin', 'benzin'),
    ('Skoda', 'Kodiaq', '2.0 TSI benzin', 'benzin'),
    ('Skoda', 'Kodiaq', '2.0 TDI dizel', 'dizel'),
    # BMW
    ('BMW', '1 Serisi', '116i benzin', 'benzin'),
    ('BMW', '1 Serisi', '118i benzin', 'benzin'),
    ('BMW', '1 Serisi', '120i benzin', 'benzin'),
    ('BMW', '1 Serisi', '116d dizel', 'dizel'),
    ('BMW', '1 Serisi', '118d dizel', 'dizel'),
    ('BMW', '3 Serisi', '316i benzin', 'benzin'),
    ('BMW', '3 Serisi', '318i benzin', 'benzin'),
    ('BMW', '3 Serisi', '320i benzin', 'benzin'),
    ('BMW', '3 Serisi', '330i benzin', 'benzin'),
    ('BMW', '3 Serisi', '316d dizel', 'dizel'),
    ('BMW', '3 Serisi', '318d dizel', 'dizel'),
    ('BMW', '3 Serisi', '320d dizel', 'dizel'),
    ('BMW', '5 Serisi', '520i benzin', 'benzin'),
    ('BMW', '5 Serisi', '530i benzin', 'benzin'),
    ('BMW', '5 Serisi', '520d dizel', 'dizel'),
    ('BMW', '5 Serisi', '530d dizel', 'dizel'),
    ('BMW', 'X1', 'sDrive18i benzin', 'benzin'),
    ('BMW', 'X1', 'xDrive20i benzin', 'benzin'),
    ('BMW', 'X1', 'sDrive18d dizel', 'dizel'),
    ('BMW', 'X1', 'xDrive20d dizel', 'dizel'),
    ('BMW', 'X3', 'xDrive20i benzin', 'benzin'),
    ('BMW', 'X3', 'xDrive30i benzin', 'benzin'),
    ('BMW', 'X3', 'xDrive20d dizel', 'dizel'),
    ('BMW', 'X3', 'xDrive30d dizel', 'dizel'),
    ('BMW', 'X5', 'xDrive40i benzin', 'benzin'),
    ('BMW', 'X5', 'M50i benzin', 'benzin'),
    ('BMW', 'X5', 'xDrive30d dizel', 'dizel'),
    ('BMW', 'X5', 'xDrive40d dizel', 'dizel'),
    # Mercedes-Benz
    ('Mercedes-Benz', 'A Serisi', 'A 160 benzin', 'benzin'),
    ('Mercedes-Benz', 'A Serisi', 'A 180 benzin', 'benzin'),
    ('Mercedes-Benz', 'A Serisi', 'A 200 benzin', 'benzin'),
    ('Mercedes-Benz', 'A Serisi', 'A 180d dizel', 'dizel'),
    ('Mercedes-Benz', 'C Serisi', 'C 180 benzin', 'benzin'),
    ('Mercedes-Benz', 'C Serisi', 'C 200 benzin', 'benzin'),
    ('Mercedes-Benz', 'C Serisi', 'C 300 benzin', 'benzin'),
    ('Mercedes-Benz', 'C Serisi', 'C 220d dizel', 'dizel'),
    ('Mercedes-Benz', 'C Serisi', 'C 250d dizel', 'dizel'),
    ('Mercedes-Benz', 'E Serisi', 'E 200 benzin', 'benzin'),
    ('Mercedes-Benz', 'E Serisi', 'E 350 benzin', 'benzin'),
    ('Mercedes-Benz', 'E Serisi', 'E 220d dizel', 'dizel'),
    ('Mercedes-Benz', 'GLC', 'GLC 200 benzin', 'benzin'),
    ('Mercedes-Benz', 'GLC', 'GLC 300 benzin', 'benzin'),
    ('Mercedes-Benz', 'GLC', 'GLC 220d dizel', 'dizel'),
    ('Mercedes-Benz', 'CLA', 'CLA 180 benzin', 'benzin'),
    ('Mercedes-Benz', 'CLA', 'CLA 200 benzin', 'benzin'),
    ('Mercedes-Benz', 'CLA', 'CLA 250 benzin', 'benzin'),
    ('Mercedes-Benz', 'GLA', 'GLA 180 benzin', 'benzin'),
    ('Mercedes-Benz', 'GLA', 'GLA 200 benzin', 'benzin'),
    # Fiat
    ('Fiat', 'Egea', '1.4 benzin', 'benzin'),
    ('Fiat', 'Egea', '1.6 Multijet dizel', 'dizel'),
    ('Fiat', 'Egea', '1.3 Multijet dizel', 'dizel'),
    ('Fiat', 'Tipo', '1.4 benzin', 'benzin'),
    ('Fiat', 'Tipo', '1.6 benzin', 'benzin'),
    ('Fiat', 'Tipo', '1.6 Multijet dizel', 'dizel'),
    ('Fiat', '500', '1.2 benzin', 'benzin'),
    ('Fiat', '500', '1.0 mHEV hibrit', 'hibrit'),
    ('Fiat', '500', '42 kWh elektrik', 'elektrik'),
    # Opel
    ('Opel', 'Corsa', '1.2 benzin', 'benzin'),
    ('Opel', 'Corsa', '1.2 Turbo benzin', 'benzin'),
    ('Opel', 'Corsa', '1.5 CDTi dizel', 'dizel'),
    ('Opel', 'Corsa', '50 kWh elektrik', 'elektrik'),
    ('Opel', 'Astra', '1.2 Turbo benzin', 'benzin'),
    ('Opel', 'Astra', '1.4 Turbo benzin', 'benzin'),
    ('Opel', 'Astra', '1.5 CDTi dizel', 'dizel'),
    ('Opel', 'Astra', '1.6 CDTi dizel', 'dizel'),
    ('Opel', 'Mokka', '1.2 Turbo benzin', 'benzin'),
    ('Opel', 'Mokka', '50 kWh elektrik', 'elektrik'),
    ('Opel', 'Crossland', '1.2 benzin', 'benzin'),
    ('Opel', 'Crossland', '1.2 Turbo benzin', 'benzin'),
    ('Opel', 'Crossland', '1.5 CDTi dizel', 'dizel'),
    ('Opel', 'Grandland', '1.2 Turbo benzin', 'benzin'),
    ('Opel', 'Grandland', '1.6 Turbo hibrit', 'hibrit'),
    # Peugeot
    ('Peugeot', '208', '1.2 PureTech benzin', 'benzin'),
    ('Peugeot', '208', '1.0 PureTech benzin', 'benzin'),
    ('Peugeot', '208', '1.5 BlueHDi dizel', 'dizel'),
    ('Peugeot', '208', '50 kWh elektrik', 'elektrik'),
    ('Peugeot', '308', '1.2 PureTech benzin', 'benzin'),
    ('Peugeot', '308', '1.6 THP benzin', 'benzin'),
    ('Peugeot', '308', '1.5 BlueHDi dizel', 'dizel'),
    ('Peugeot', '308', '1.6 BlueHDi dizel', 'dizel'),
    ('Peugeot', '3008', '1.2 PureTech benzin', 'benzin'),
    ('Peugeot', '3008', '1.6 THP benzin', 'benzin'),
    ('Peugeot', '3008', '1.5 BlueHDi dizel', 'dizel'),
    ('Peugeot', '3008', '2.0 BlueHDi dizel', 'dizel'),
    ('Peugeot', '3008', '1.6 PHR hibrit', 'hibrit'),
    ('Peugeot', '5008', '1.2 PureTech benzin', 'benzin'),
    ('Peugeot', '5008', '1.6 THP benzin', 'benzin'),
    ('Peugeot', '5008', '1.5 BlueHDi dizel', 'dizel'),
    ('Peugeot', '5008', '2.0 BlueHDi dizel', 'dizel'),
    # Seat
    ('Seat', 'Leon', '1.0 TSI benzin', 'benzin'),
    ('Seat', 'Leon', '1.5 TSI benzin', 'benzin'),
    ('Seat', 'Leon', '2.0 TSI benzin', 'benzin'),
    ('Seat', 'Leon', '1.6 TDI dizel', 'dizel'),
    ('Seat', 'Leon', '2.0 TDI dizel', 'dizel'),
    ('Seat', 'Leon', '1.4 TSI eHybrid hibrit', 'hibrit'),
    ('Seat', 'Ibiza', '1.0 MPI benzin', 'benzin'),
    ('Seat', 'Ibiza', '1.0 TSI benzin', 'benzin'),
    ('Seat', 'Ibiza', '1.5 TSI benzin', 'benzin'),
    ('Seat', 'Ateca', '1.0 TSI benzin', 'benzin'),
    ('Seat', 'Ateca', '1.5 TSI benzin', 'benzin'),
    ('Seat', 'Ateca', '2.0 TDI dizel', 'dizel'),
    ('Seat', 'Arona', '1.0 TSI benzin', 'benzin'),
    ('Seat', 'Arona', '1.5 TSI benzin', 'benzin'),
    # Nissan
    ('Nissan', 'Qashqai', '1.3 DIG-T benzin', 'benzin'),
    ('Nissan', 'Qashqai', '1.5 e-Power hibrit', 'hibrit'),
    ('Nissan', 'Qashqai', '1.7 dCi dizel', 'dizel'),
    ('Nissan', 'Juke', '1.0 DIG-T benzin', 'benzin'),
    ('Nissan', 'Juke', '1.5 dCi dizel', 'dizel'),
    ('Nissan', 'Leaf', '40 kWh elektrik', 'elektrik'),
    ('Nissan', 'Leaf', '62 kWh elektrik', 'elektrik'),
    ('Nissan', 'X-Trail', '1.3 DIG-T benzin', 'benzin'),
    ('Nissan', 'X-Trail', '1.5 e-4ORCE hibrit', 'hibrit'),
    ('Nissan', 'X-Trail', '1.7 dCi dizel', 'dizel'),
    # Mazda
    ('Mazda', 'Mazda3', '1.5 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'Mazda3', '2.0 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'Mazda3', '2.0 e-SKYACTIV X hibrit', 'hibrit'),
    ('Mazda', 'Mazda6', '2.0 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'Mazda6', '2.5 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'Mazda6', '2.0 SKYACTIV-D dizel', 'dizel'),
    ('Mazda', 'CX-5', '2.0 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'CX-5', '2.5 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'CX-5', '2.2 SKYACTIV-D dizel', 'dizel'),
    ('Mazda', 'CX-30', '2.0 SKYACTIV-G benzin', 'benzin'),
    ('Mazda', 'CX-30', '2.0 e-SKYACTIV X hibrit', 'hibrit'),
    # Mitsubishi
    ('Mitsubishi', 'Eclipse Cross', '1.5T benzin', 'benzin'),
    ('Mitsubishi', 'Eclipse Cross', '2.4 PHEV hibrit', 'hibrit'),
    ('Mitsubishi', 'Outlander', '2.0 benzin', 'benzin'),
    ('Mitsubishi', 'Outlander', '2.4 PHEV hibrit', 'hibrit'),
    ('Mitsubishi', 'L200', '2.4 DI-D dizel', 'dizel'),
    # Subaru
    ('Subaru', 'Outback', '2.5 BOXER benzin', 'benzin'),
    ('Subaru', 'Outback', '2.5 e-BOXER hibrit', 'hibrit'),
    ('Subaru', 'Forester', '2.0i BOXER benzin', 'benzin'),
    ('Subaru', 'Forester', '2.0e-BOXER hibrit', 'hibrit'),
    ('Subaru', 'XV', '2.0i BOXER benzin', 'benzin'),
    ('Subaru', 'XV', '2.0e-BOXER hibrit', 'hibrit'),
    # Volvo
    ('Volvo', 'XC60', 'B4 benzin', 'benzin'),
    ('Volvo', 'XC60', 'B5 benzin', 'benzin'),
    ('Volvo', 'XC60', 'D4 dizel', 'dizel'),
    ('Volvo', 'XC60', 'T6 Recharge hibrit', 'hibrit'),
    ('Volvo', 'S60', 'B4 benzin', 'benzin'),
    ('Volvo', 'S60', 'B5 benzin', 'benzin'),
    ('Volvo', 'S60', 'T8 Recharge hibrit', 'hibrit'),
    ('Volvo', 'XC40', 'B3 benzin', 'benzin'),
    ('Volvo', 'XC40', 'B4 benzin', 'benzin'),
    ('Volvo', 'XC40', '69 kWh elektrik', 'elektrik'),
    ('Volvo', 'XC40', '82 kWh elektrik', 'elektrik'),
    # Audi
    ('Audi', 'A3', '1.0 TFSI benzin', 'benzin'),
    ('Audi', 'A3', '1.4 TFSI benzin', 'benzin'),
    ('Audi', 'A3', '1.5 TFSI benzin', 'benzin'),
    ('Audi', 'A3', '2.0 TFSI benzin', 'benzin'),
    ('Audi', 'A3', '2.0 TDI dizel', 'dizel'),
    ('Audi', 'A3', '1.4 TFSI e hibrit', 'hibrit'),
    ('Audi', 'A4', '1.4 TFSI benzin', 'benzin'),
    ('Audi', 'A4', '2.0 TFSI benzin', 'benzin'),
    ('Audi', 'A4', '2.0 TDI dizel', 'dizel'),
    ('Audi', 'A4', '3.0 TDI dizel', 'dizel'),
    ('Audi', 'Q3', '1.5 TFSI benzin', 'benzin'),
    ('Audi', 'Q3', '35 TFSI benzin', 'benzin'),
    ('Audi', 'Q3', '35 TDI dizel', 'dizel'),
    ('Audi', 'Q5', '40 TFSI benzin', 'benzin'),
    ('Audi', 'Q5', '45 TFSI benzin', 'benzin'),
    ('Audi', 'Q5', '40 TDI dizel', 'dizel'),
    ('Audi', 'Q5', '55 TFSI e hibrit', 'hibrit'),
    # Suzuki
    ('Suzuki', 'Swift', '1.0 Boosterjet benzin', 'benzin'),
    ('Suzuki', 'Swift', '1.2 SHVS hibrit', 'hibrit'),
    ('Suzuki', 'Swift', '1.2 benzin', 'benzin'),
    ('Suzuki', 'Vitara', '1.0 Boosterjet benzin', 'benzin'),
    ('Suzuki', 'Vitara', '1.4 Boosterjet benzin', 'benzin'),
    ('Suzuki', 'Vitara', '1.5 hibrit', 'hibrit'),
    ('Suzuki', 'SX4', '1.0 Boosterjet benzin', 'benzin'),
    ('Suzuki', 'SX4', '1.4 Boosterjet benzin', 'benzin'),
    ('Suzuki', 'Jimny', '1.5 benzin', 'benzin'),
    # Jeep
    ('Jeep', 'Renegade', '1.0T benzin', 'benzin'),
    ('Jeep', 'Renegade', '1.3T benzin', 'benzin'),
    ('Jeep', 'Renegade', '1.6 MJD dizel', 'dizel'),
    ('Jeep', 'Renegade', '1.3 PHEV hibrit', 'hibrit'),
    ('Jeep', 'Compass', '1.3T benzin', 'benzin'),
    ('Jeep', 'Compass', '1.5T benzin', 'benzin'),
    ('Jeep', 'Compass', '1.6 MJD dizel', 'dizel'),
    ('Jeep', 'Compass', '1.3 PHEV hibrit', 'hibrit'),
    # Citroen
    ('Citroen', 'C3', '1.2 PureTech benzin', 'benzin'),
    ('Citroen', 'C3', '1.0 PureTech benzin', 'benzin'),
    ('Citroen', 'C5 X', '1.2 PureTech benzin', 'benzin'),
    ('Citroen', 'C5 X', '1.6 PureTech hibrit', 'hibrit'),
    ('Citroen', 'Berlingo', '1.2 PureTech benzin', 'benzin'),
    ('Citroen', 'Berlingo', '1.5 BlueHDi dizel', 'dizel'),
    # Alfa Romeo
    ('Alfa Romeo', 'Giulia', '2.0 Turbo benzin', 'benzin'),
    ('Alfa Romeo', 'Giulia', '2.2 Turbo dizel', 'dizel'),
    ('Alfa Romeo', 'Stelvio', '2.0 Turbo benzin', 'benzin'),
    ('Alfa Romeo', 'Stelvio', '2.2 Turbo dizel', 'dizel'),
    # Porsche
    ('Porsche', 'Cayenne', '3.0T benzin', 'benzin'),
    ('Porsche', 'Cayenne', 'S 2.9T benzin', 'benzin'),
    ('Porsche', 'Cayenne', '4.0T benzin', 'benzin'),
    ('Porsche', 'Cayenne', 'E-Hybrid hibrit', 'hibrit'),
    ('Porsche', 'Macan', '2.0 benzin', 'benzin'),
    ('Porsche', 'Macan', 'S 3.0 benzin', 'benzin'),
    ('Porsche', 'Macan', 'GTS 2.9 benzin', 'benzin'),
    ('Porsche', 'Taycan', '79.2 kWh elektrik', 'elektrik'),
    ('Porsche', 'Taycan', '93.4 kWh elektrik', 'elektrik'),
    # Toyota additions
    ('Toyota', 'Prius', '1.8 HEV hibrit', 'hibrit'),
    ('Toyota', 'Corolla Cross', '1.2T benzin', 'benzin'),
    ('Toyota', 'Corolla Cross', '1.8 HEV hibrit', 'hibrit'),
    ('Toyota', 'Corolla Cross', '2.0 HEV hibrit', 'hibrit'),
    ('Toyota', 'bZ4X', '71.4 kWh elektrik', 'elektrik'),
    # Volkswagen additions
    ('Volkswagen', 'ID.3', '45 kWh elektrik', 'elektrik'),
    ('Volkswagen', 'ID.3', '58 kWh elektrik', 'elektrik'),
    ('Volkswagen', 'ID.3', '77 kWh elektrik', 'elektrik'),
    ('Volkswagen', 'ID.4', '52 kWh elektrik', 'elektrik'),
    ('Volkswagen', 'ID.4', '77 kWh elektrik', 'elektrik'),
    ('Volkswagen', 'Caddy', '1.5 TSI benzin', 'benzin'),
    ('Volkswagen', 'Caddy', '2.0 TDI dizel', 'dizel'),
    # Renault additions
    ('Renault', 'Symbol', '1.0 SCe benzin', 'benzin'),
    ('Renault', 'Symbol', '1.5 dCi dizel', 'dizel'),
    ('Renault', 'Talisman', '1.3 TCe benzin', 'benzin'),
    ('Renault', 'Talisman', '1.6 dCi dizel', 'dizel'),
    ('Renault', 'Austral', '1.3 TCe benzin', 'benzin'),
    ('Renault', 'Austral', '1.2 E-Tech hibrit', 'hibrit'),
    ('Renault', 'Zoe', '52 kWh elektrik', 'elektrik'),
    # Ford additions
    ('Ford', 'Tourneo Courier', '1.0 EcoBoost benzin', 'benzin'),
    ('Ford', 'Tourneo Courier', '1.5 EcoBlue dizel', 'dizel'),
    # Honda additions
    ('Honda', 'Jazz', '1.5 e:HEV hibrit', 'hibrit'),
    # Hyundai additions
    ('Hyundai', 'i10', '1.0 MPI benzin', 'benzin'),
    ('Hyundai', 'i10', '1.0 T-GDI benzin', 'benzin'),
    ('Hyundai', 'IONIQ 6', '53 kWh elektrik', 'elektrik'),
    ('Hyundai', 'IONIQ 6', '77.4 kWh elektrik', 'elektrik'),
    # Kia additions
    ('Kia', 'Rio', '1.0 T-GDI benzin', 'benzin'),
    ('Kia', 'Rio', '1.2 MPI benzin', 'benzin'),
    ('Kia', 'EV9', '76.1 kWh elektrik', 'elektrik'),
    ('Kia', 'EV9', '99.8 kWh elektrik', 'elektrik'),
    # Dacia additions
    ('Dacia', 'Jogger', '1.0 TCe benzin', 'benzin'),
    # Skoda additions
    ('Skoda', 'Enyaq', '58 kWh elektrik', 'elektrik'),
    ('Skoda', 'Enyaq', '77 kWh elektrik', 'elektrik'),
    ('Skoda', 'Scala', '1.0 TSI benzin', 'benzin'),
    ('Skoda', 'Scala', '1.5 TSI benzin', 'benzin'),
    # BMW additions
    ('BMW', '2 Serisi', '218i benzin', 'benzin'),
    ('BMW', '2 Serisi', '220i benzin', 'benzin'),
    ('BMW', 'i4', 'eDrive35 elektrik', 'elektrik'),
    ('BMW', 'i4', 'eDrive40 elektrik', 'elektrik'),
    ('BMW', 'iX3', '74 kWh elektrik', 'elektrik'),
    # Mercedes additions
    ('Mercedes-Benz', 'GLE', 'GLE 350d dizel', 'dizel'),
    ('Mercedes-Benz', 'GLE', 'GLE 400 benzin', 'benzin'),
    ('Mercedes-Benz', 'GLB', 'GLB 180 benzin', 'benzin'),
    ('Mercedes-Benz', 'GLB', 'GLB 200d dizel', 'dizel'),
    ('Mercedes-Benz', 'EQA', '66.5 kWh elektrik', 'elektrik'),
    # Fiat additions
    ('Fiat', 'Panda', '1.0 Mild Hybrid benzin', 'benzin'),
    ('Fiat', 'Panda', '1.2 benzin', 'benzin'),
    ('Fiat', 'Doblo', '1.5 benzin', 'benzin'),
    ('Fiat', 'Doblo', '1.5 Multijet dizel', 'dizel'),
    # Opel additions
    ('Opel', 'Combo', '1.2 Turbo benzin', 'benzin'),
    ('Opel', 'Combo', '1.5 CDTi dizel', 'dizel'),
    # Citroen additions
    ('Citroen', 'C4', '1.2 PureTech benzin', 'benzin'),
    ('Citroen', 'C4', '50 kWh elektrik', 'elektrik'),
    # Peugeot additions
    ('Peugeot', '2008', '1.2 PureTech benzin', 'benzin'),
    ('Peugeot', '2008', '1.5 BlueHDi dizel', 'dizel'),
    ('Peugeot', '2008', '50 kWh elektrik', 'elektrik'),
    # Seat additions
    ('Seat', 'Tarraco', '1.5 TSI benzin', 'benzin'),
    ('Seat', 'Tarraco', '2.0 TDI dizel', 'dizel'),
    # Audi additions
    ('Audi', 'A6', '40 TFSI benzin', 'benzin'),
    ('Audi', 'A6', '45 TFSI benzin', 'benzin'),
    ('Audi', 'A6', '40 TDI dizel', 'dizel'),
    ('Audi', 'A6', '45 TDI dizel', 'dizel'),
    ('Audi', 'Q7', '45 TFSI benzin', 'benzin'),
    ('Audi', 'Q7', '55 TFSI benzin', 'benzin'),
    ('Audi', 'Q7', '45 TDI dizel', 'dizel'),
    # Tesla (new brand)
    ('Tesla', 'Model 3', 'Standard Range elektrik', 'elektrik'),
    ('Tesla', 'Model 3', 'Long Range elektrik', 'elektrik'),
    ('Tesla', 'Model 3', 'Performance elektrik', 'elektrik'),
    ('Tesla', 'Model Y', 'Long Range elektrik', 'elektrik'),
    ('Tesla', 'Model Y', 'Performance elektrik', 'elektrik'),
    # Cupra (new brand)
    ('Cupra', 'Formentor', '1.0 TSI benzin', 'benzin'),
    ('Cupra', 'Formentor', '1.5 TSI benzin', 'benzin'),
    ('Cupra', 'Formentor', '2.0 TSI benzin', 'benzin'),
    ('Cupra', 'Formentor', '1.4 e-Hybrid hibrit', 'hibrit'),
    ('Cupra', 'Born', '45 kWh elektrik', 'elektrik'),
    ('Cupra', 'Born', '58 kWh elektrik', 'elektrik'),
    ('Cupra', 'Born', '77 kWh elektrik', 'elektrik'),
]

MAINTENANCE_TEMPLATES = [
    # ── Benzin ───────────────────────────────────────────────────────────────
    ('benzin', 'Motor Yağı + Filtre Değişimi',
     'yağ,oil,motor yağ,engine oil,yag degisim',
     10000, 12, 1500, 4000, 'critical',
     'Benzinli araçlarda en kritik bakım. 10.000 km veya 1 yılda bir yapılmalı.'),
    ('benzin', 'Hava Filtresi Değişimi',
     'hava filtre,air filter,hava filtresi',
     20000, 18, 300, 800, 'important',
     'Kirli hava filtresi yakıt tüketimini artırır ve motoru koruyamaz.'),
    ('benzin', 'Polen Filtresi Değişimi',
     'polen,cabin filter,kabin filtre',
     15000, 12, 150, 500, 'routine',
     'Klimanın ve kabin havasının temizliği için önemlidir.'),
    ('benzin', 'Buji Değişimi',
     'buji,spark plug,ateşleme',
     40000, 36, 600, 2500, 'important',
     'Platin/iridyum bujiler 60.000-80.000 km dayanır. Standart bujiler 30.000 km.'),
    ('benzin', 'Fren Balata Değişimi (Ön)',
     'fren bala,brake pad,ön balata',
     30000, 24, 800, 3000, 'critical',
     'Ön fren balataları arka balatalara göre daha hızlı aşınır.'),
    ('benzin', 'Fren Diski Değişimi (Ön)',
     'fren disk,brake disc,ön disk',
     70000, 60, 1500, 5000, 'important',
     'Diskler balata değişiminin 2 katı ömre sahiptir.'),
    ('benzin', 'Fren Hidroliği Değişimi',
     'fren hidrolik,brake fluid,fren yağ',
     40000, 24, 300, 700, 'important',
     'Fren hidroliği nem çeker, zamanla bozulur.'),
    ('benzin', 'Antifriz/Soğutma Suyu Değişimi',
     'antifriz,soğutma,coolant,antifriz degisim',
     40000, 24, 400, 900, 'important',
     'Antifriz pH dengesi bozulursa motor hasarına yol açabilir.'),
    ('benzin', 'Triger Kayışı/Zinciri Değişimi',
     'triger,kayış,timing belt,timing chain,zamanlama',
     90000, 72, 2000, 6000, 'critical',
     'Triger kayışı kopması motoru tamamen mahvedebilir. Süresinde değiştirilmeli!'),
    ('benzin', 'Manuel Şanzıman Yağı Değişimi',
     'şanzıman yağ,gearbox oil,vites yağ,manuel şanzıman',
     60000, 60, 500, 1200, 'important',
     'Manuel şanzımanlarda yağ değişimi vites geçişlerini iyileştirir.'),
    ('benzin', 'Otomatik Şanzıman Yağı Değişimi',
     'otomatik şanzıman,atf,transmission fluid,dsg,cvt',
     60000, 60, 1500, 5000, 'important',
     'Otomatik şanzıman yağı değişimi pahalı arızaları önler.'),
    ('benzin', 'Lastik Rotasyonu',
     'lastik rotasyon,tire rotation,dönme',
     10000, 6, 150, 400, 'routine',
     'Lastik rotasyonu düzgün aşınmayı sağlar, lastik ömrünü uzatır.'),
    ('benzin', 'Akü Kontrolü/Değişimi',
     'akü,batarya,battery,aküde sorun',
     None, 48, 1000, 3500, 'important',
     'Akü ömrü genellikle 4-5 yıldır. Kış öncesi kontrol önerilir.'),
    ('benzin', 'Debriyaj Değişimi',
     'debriyaj,clutch,kavrama',
     90000, None, 3000, 8000, 'important',
     'Manuel vitesin olmazsa olmazı. 80.000-120.000 km arasında değişim gerekebilir.'),
    # ── Dizel ────────────────────────────────────────────────────────────────
    ('dizel', 'Motor Yağı + Filtre Değişimi',
     'yağ,oil,motor yağ,engine oil,yag degisim',
     10000, 12, 2000, 5000, 'critical',
     'Dizel araçlarda özel yağ ve filtre kullanılmalıdır. Düzenli değişim şarttır.'),
    ('dizel', 'Dizel Yakıt Filtresi Değişimi',
     'yakıt filtre,fuel filter,dizel filtre,mazot filtre',
     25000, 18, 500, 1800, 'critical',
     'Dizel araçlarda yakıt filtresi kritiktir. Kirli filtre enjektör hasarına yol açar.'),
    ('dizel', 'Hava Filtresi Değişimi',
     'hava filtre,air filter,hava filtresi',
     20000, 18, 400, 1000, 'important',
     'Dizel araçlarda hava filtresi düzenli değiştirilmelidir.'),
    ('dizel', 'Polen Filtresi Değişimi',
     'polen,cabin filter,kabin filtre',
     15000, 12, 150, 500, 'routine',
     'Kabin hava kalitesi için önemlidir.'),
    ('dizel', 'Fren Balata Değişimi (Ön)',
     'fren bala,brake pad,ön balata',
     40000, 30, 800, 3000, 'critical',
     'Dizel araçlar motor freni kullanır, ön balata ömrü benzinlilere göre daha uzun olabilir.'),
    ('dizel', 'Fren Diski Değişimi (Ön)',
     'fren disk,brake disc,ön disk',
     80000, 72, 1500, 5000, 'important',
     'Dizel araçlarda fren diskleri daha uzun ömürlüdür.'),
    ('dizel', 'Fren Hidroliği Değişimi',
     'fren hidrolik,brake fluid,fren yağ',
     40000, 24, 300, 700, 'important',
     'Fren güvenliği için kritik sıvıdır.'),
    ('dizel', 'Antifriz/Soğutma Suyu Değişimi',
     'antifriz,soğutma,coolant',
     40000, 24, 400, 900, 'important',
     'Dizel motorlar yüksek sıcaklıkta çalışır, soğutma sistemi çok önemlidir.'),
    ('dizel', 'Triger Kayışı/Zinciri Değişimi',
     'triger,kayış,timing belt,timing chain,zamanlama',
     100000, 84, 2500, 8000, 'critical',
     'Dizel araçlarda triger hasarı motor revizyonu anlamına gelir!'),
    ('dizel', 'DPF (Partikül Filtresi) Temizliği',
     'dpf,partikül filtre,is filtre,soot filter',
     120000, None, 2000, 6000, 'important',
     'DPF tıkanması ciddi motor sorunlarına yol açar. Kısa mesafe kullanımında daha sık gerekebilir.'),
    ('dizel', 'EGR Temizliği',
     'egr,egr temizlik,exhaust gas recirculation',
     80000, None, 1000, 4000, 'important',
     'EGR tıkanması güç kaybına ve yakıt tüketimi artışına neden olur.'),
    ('dizel', 'Lastik Rotasyonu',
     'lastik rotasyon,tire rotation',
     10000, 6, 150, 400, 'routine',
     'Lastik ömrünü uzatmak için önerilir.'),
    ('dizel', 'Manuel Şanzıman Yağı Değişimi',
     'şanzıman yağ,gearbox oil,vites yağ',
     60000, 60, 500, 1200, 'important',
     'Dizel araçlarda yüksek tork nedeniyle şanzıman yağı daha zorlanır.'),
    ('dizel', 'Otomatik Şanzıman Yağı Değişimi',
     'otomatik şanzıman,atf,transmission fluid',
     60000, 60, 1500, 5000, 'important',
     'Otomatik şanzıman yağı değişimi ihmal edilmemeli.'),
    ('dizel', 'Akü Kontrolü/Değişimi',
     'akü,batarya,battery',
     None, 48, 1200, 4000, 'important',
     'Dizel araçlarda daha büyük ve güçlü akü gereklidir, 4-5 yılda değişim.'),
    # ── LPG ──────────────────────────────────────────────────────────────────
    ('lpg', 'Motor Yağı + Filtre Değişimi',
     'yağ,oil,motor yağ,yag degisim',
     7500, 6, 1500, 4000, 'critical',
     'LPG araçlarda yağ daha hızlı bozulur. 7.500 km veya 6 ayda bir değiştirilmeli!'),
    ('lpg', 'LPG Filtresi Değişimi',
     'lpg filtre,gaz filtre,likit filtre',
     10000, 12, 200, 600, 'critical',
     'LPG filtreleri benzin filtrelerine göre daha sık değiştirilmelidir.'),
    ('lpg', 'LPG Enjektör Bakımı',
     'lpg enjektör,gaz enjektör,lpg bakim',
     20000, 12, 500, 2000, 'important',
     'LPG enjektörleri düzenli temizlenmeli ve bakımı yapılmalıdır.'),
    ('lpg', 'Buji Değişimi',
     'buji,spark plug',
     20000, 24, 400, 1500, 'important',
     'LPG daha yüksek yanma sıcaklığına sahiptir, bujiler daha sık değiştirilmeli.'),
    ('lpg', 'Hava Filtresi Değişimi',
     'hava filtre,air filter',
     20000, 18, 300, 800, 'important',
     'LPG araçlarda hava filtresi standart aralıklarda değiştirilmeli.'),
    ('lpg', 'LPG Depo Muayenesi',
     'lpg depo,tüp muayene,tank muayene',
     None, 120, 500, 1500, 'critical',
     'LPG tüpleri yasal olarak 10 yılda bir zorunlu muayeneden geçmelidir!'),
    ('lpg', 'Fren Balata Değişimi (Ön)',
     'fren bala,brake pad',
     30000, 24, 800, 3000, 'critical',
     'LPG araçlarda fren bakımı benzinli araçlarla aynı frekanstadır.'),
    ('lpg', 'Triger Kayışı Değişimi',
     'triger,kayış,timing belt',
     90000, 72, 2000, 6000, 'critical',
     'LPG araçlarda triger kayışı özellikle önemlidir.'),
    ('lpg', 'Antifriz Değişimi',
     'antifriz,soğutma,coolant',
     40000, 24, 400, 900, 'important',
     'Soğutma sistemi sağlığı LPG araçlarda kritiktir.'),
    ('lpg', 'Lastik Rotasyonu',
     'lastik rotasyon,tire rotation',
     10000, 6, 150, 400, 'routine',
     'Lastik rotasyonu tüm araçlar için önerilir.'),
    # ── Elektrik ─────────────────────────────────────────────────────────────
    ('elektrik', 'Fren Balata Değişimi (Ön)',
     'fren bala,brake pad,ön balata',
     60000, 48, 800, 2500, 'important',
     'EV araçlarda rejeneratif frenleme nedeniyle balata ömrü daha uzundur.'),
    ('elektrik', 'Fren Hidroliği Değişimi',
     'fren hidrolik,brake fluid',
     40000, 24, 300, 700, 'important',
     'EV araçlarda fren hidroliği yine de değiştirilmelidir.'),
    ('elektrik', 'Polen Filtresi Değişimi',
     'polen,cabin filter,kabin filtre',
     20000, 12, 150, 500, 'routine',
     'EV araçlarda kabin filtresi standart bakımın parçasıdır.'),
    ('elektrik', 'Klima/Isı Pompası Servisi',
     'klima servis,klima bakım,heat pump,ısı pompası',
     30000, 24, 500, 2000, 'important',
     'EV araçlarda ısı pompası menzili ve batarya sağlığını etkiler.'),
    ('elektrik', 'Batarya Soğutma Sıvısı Değişimi',
     'batarya soğutma,termal yönetim,coolant,soğutma sıvı',
     80000, 60, 500, 2500, 'important',
     'Batarya soğutma sistemi sağlığı menzil ve batarya ömrü için kritiktir.'),
    ('elektrik', 'Diferansiyel/Redüktör Yağı',
     'diferansiyel yağ,redüktör,gear oil',
     50000, 48, 500, 1500, 'important',
     'EV araçlarda redüktör yağı değişimi gereklidir.'),
    ('elektrik', 'Lastik Rotasyonu',
     'lastik rotasyon,tire rotation',
     10000, 6, 150, 400, 'routine',
     'EV araçlar ağır olduğundan lastikler daha hızlı aşınır, rotasyon önemlidir.'),
    # ── Hibrit ───────────────────────────────────────────────────────────────
    ('hibrit', 'Motor Yağı + Filtre Değişimi',
     'yağ,oil,motor yağ,yag degisim',
     15000, 12, 1500, 4000, 'critical',
     'Hibrit araçlarda motor daha az çalışır ama yağ yine de bozulur.'),
    ('hibrit', 'Hava Filtresi Değişimi',
     'hava filtre,air filter',
     30000, 24, 300, 800, 'important',
     'Hibrit araçlarda motor daha az yüklüdür, hava filtresi ömrü uzundur.'),
    ('hibrit', 'Polen Filtresi Değişimi',
     'polen,cabin filter',
     15000, 12, 150, 500, 'routine',
     'Kabin hava kalitesi için önemlidir.'),
    ('hibrit', 'Fren Balata Değişimi (Ön)',
     'fren bala,brake pad',
     60000, 48, 800, 2500, 'important',
     'Hibrit araçlarda rejeneratif frenleme balata ömrünü önemli ölçüde uzatır.'),
    ('hibrit', 'Hibrit Batarya Soğutma Sistemi',
     'hibrit batarya,soğutma sistem,hybrid battery',
     80000, 60, 500, 2000, 'important',
     'Hibrit batarya soğutması arıza yapmaması için kontrol edilmelidir.'),
    ('hibrit', 'Triger Kayışı/Zinciri',
     'triger,kayış,timing',
     120000, 96, 2000, 7000, 'critical',
     'Hibrit araçlarda motor daha az çalışsa da triger değişimi şarttır.'),
    ('hibrit', 'Antifriz Değişimi',
     'antifriz,soğutma,coolant',
     40000, 24, 400, 900, 'important',
     'Hibrit araçlarda iki ayrı soğutma devresi olabilir.'),
    ('hibrit', 'Lastik Rotasyonu',
     'lastik rotasyon,tire rotation',
     10000, 6, 150, 400, 'routine',
     'Lastik rotasyonu tüm hibrit araçlar için önerilir.'),
    ('hibrit', 'Akü (12V) Kontrolü/Değişimi',
     'akü,12v batarya,battery',
     None, 48, 1200, 3500, 'important',
     'Hibrit araçlarda ayrı bir 12V akü bulunur ve 4-5 yılda değiştirilmelidir.'),
]


# ── Kronik Arıza Veritabanı ──────────────────────────────────────────────────
# Format: (brand, model, year_from, year_to, title, description, category, severity, approx_km)
# year_to = None → hâlâ geçerli; approx_km = None → km bağımsız
CHRONIC_FAULTS = [
    # ── Toyota ───────────────────────────────────────────────────────────────
    ('Toyota', 'Corolla', 2013, 2019, 'Vites Körüğü Çatlama',
     'Manuel vitesli modellerde vites körüğünün plastik kısmı zamanla çatlayabilir.',
     'karoser', 'low', 80000),
    ('Toyota', 'Corolla', 2019, None, 'Hibrit Akü Havalandırma Tıkanması',
     'Arka koltuk altındaki hibrit akü havalandırma kanalı toz/kir ile tıkanabilir. '
     'Aşırı ısınmayı önlemek için yıllık temizlik önerilir.',
     'elektrik', 'medium', None),
    ('Toyota', 'Yaris', 2011, 2020, 'Arka Silecek Motor Arızası',
     'Arka silecek motoru nem nedeniyle kısa sürede bozulabilir.',
     'elektrik', 'low', 60000),
    ('Toyota', 'RAV4', 2013, 2018, 'Arka Diferansiyel Salmastra Sızıntısı',
     '4WD modellerinde arka diferansiyel salmastrasından yağ sızıntısı görülmektedir.',
     'mekanik', 'medium', 70000),
    ('Toyota', 'Hilux', 2015, None, 'Egzoz Manifold Cıvata Kırılması',
     'Egzoz manifold cıvataları ısı döngüsü nedeniyle zamanla kırılabilir, tıkırtı sesine yol açar.',
     'egzoz', 'medium', 100000),
    # ── Volkswagen ───────────────────────────────────────────────────────────
    ('Volkswagen', 'Golf', 2013, 2020, 'DSG Vites Kutusu Titreşim',
     'Düşük hızlarda DSG çift kavramalı şanzıman titreşim ve sarsıntı yapabilir. '
     'Mekatronik ünitesi arızalanabilir; mekatronik güncellemesi veya değişimi gerekebilir.',
     'sanziman', 'high', 50000),
    ('Volkswagen', 'Golf', 2013, 2020, 'Su Pompası Arızası (1.4 TSI)',
     '1.4 TSI motorlarda plastik su pompası erken arıza yapabilir. '
     'Aşırı ısınma riskini önlemek için 80.000 km\'de değişim önerilir.',
     'sogutma', 'high', 80000),
    ('Volkswagen', 'Polo', 2014, 2017, 'Isıtma Rezistansı Arızası',
     'Kabin ısıtma rezistansı arızalanınca ısıtma çalışmaz hale gelebilir.',
     'klima', 'medium', 60000),
    ('Volkswagen', 'Passat', 2015, None, 'AdBlue Pompası Arızası (Dizel)',
     'Dizel modellerde AdBlue pompası soğukta çalışmayabilir veya arızalanabilir.',
     'egzoz', 'medium', 80000),
    ('Volkswagen', 'Tiguan', 2017, None, 'Haldex Kavrama Sızıntısı (4Motion)',
     '4Motion AWD sistemindeki Haldex kavramasından yağ sızıntısı görülebilir. '
     '40.000 km\'de Haldex yağı değişimi şart.',
     'mekanik', 'medium', 60000),
    # ── Renault ──────────────────────────────────────────────────────────────
    ('Renault', 'Megane', 2015, 2022, 'Cam Krikosu Motor Arızası',
     'Ön ve arka cam krikosu motorları arızalanarak camın inmesine/çıkmamasına neden olabilir.',
     'elektrik', 'low', 60000),
    ('Renault', 'Megane', 2015, 2022, 'Vites Körüğü Titreşimi (EDC)',
     'EDC otomatik vitesli modellerde düşük hızda titreşim ve gecikmeli vites değişimi olabilir.',
     'sanziman', 'medium', 40000),
    ('Renault', 'Clio', 2012, 2019, 'Termostat Arızası',
     'Motor termostası erken arızalanabilir, motor çalışma sıcaklığına geç ulaşır.',
     'sogutma', 'medium', 80000),
    ('Renault', 'Fluence', 2012, 2019, 'Direksiyon Pompası Gürültüsü',
     'Hidrolik direksiyon pompası soğuk havalarda vınlama sesi çıkarabilir.',
     'direksiyon', 'low', 70000),
    ('Renault', 'Duster', 2012, 2018, 'Arka Tekerlek Yatağı Aşınması',
     'Arka tekerlek yatakları öngörülenden erken aşınabilir, uğultu sesi çıkarır.',
     'sasi', 'medium', 60000),
    # ── Ford ─────────────────────────────────────────────────────────────────
    ('Ford', 'Focus', 2014, 2019, 'PowerShift Şanzıman Titreşimi',
     'PowerShift çift kavramalı şanzıman titreşim, gecikmeli vites değişimi ve bazen arıza ışığı '
     'yanar. Şanzıman yazılım güncellemesi ve/veya mekatronik değişimi gerekebilir.',
     'sanziman', 'high', 30000),
    ('Ford', 'Focus', 2014, 2019, 'Su Pompası ve Termostat Arızası (1.0 EcoBoost)',
     '1.0 EcoBoost motorlarda su pompası ve termostat birlikte arıza yapabilir, '
     'motor aşırı ısınabilir.',
     'sogutma', 'high', 90000),
    ('Ford', 'Fiesta', 2013, 2022, 'Cam Krikosu Arızası',
     'Ön camların krikosu zamanla arızalanarak cam inmesine neden olabilir.',
     'elektrik', 'low', 70000),
    ('Ford', 'Kuga', 2013, 2019, 'Soğutma Sistemi Arızası (1.5 EcoBoost)',
     '1.5 EcoBoost motorlu modellerde soğutma sistemi zafiyeti nedeniyle motor hasarı '
     'görülebilir. Bu konuda resmi servis kampanyası açılmıştır.',
     'sogutma', 'critical', 60000),
    ('Ford', 'Ranger', 2015, None, 'Arka Fren Diski Paslanması',
     'Araç uzun süre kullanılmadığında arka fren diskleri hızla paslanabilir.',
     'fren', 'low', None),
    # ── Honda ────────────────────────────────────────────────────────────────
    ('Honda', 'Civic', 2016, 2022, 'Klima Kompresör Titreşimi',
     'Klima açıkken motor bölümünden titreşim ve düzensiz rölanti hissedilebilir.',
     'klima', 'low', 50000),
    ('Honda', 'CR-V', 2018, None, 'Motor Yağına Su Karışması (1.5 Turbo)',
     '1.5 turbo motorlarda soğuk iklimlerde kısa yolculuklarda yağa yakıt/su karışması '
     'rapor edilmiştir. Düzenli uzun sürüş önerilir.',
     'motor', 'high', None),
    ('Honda', 'HR-V', 2015, 2022, 'CVT Şanzıman Gürültüsü',
     'CVT şanzımanlı modellerde yüksek devirde metalik vınlama sesi duyulabilir.',
     'sanziman', 'medium', 80000),
    # ── Hyundai ──────────────────────────────────────────────────────────────
    ('Hyundai', 'i20', 2012, 2020, 'Ön Amortisör Sesi',
     'Ön amortisörler ve üst tampon yatakları erken aşınabilir; bozuk yolda "tak tak" sesi çıkar.',
     'sasi', 'medium', 50000),
    ('Hyundai', 'i30', 2012, 2017, 'Egzoz Paslanması',
     'Orta boru bağlantıları özellikle kış koşullarında hızlı paslanabilir.',
     'egzoz', 'low', 80000),
    ('Hyundai', 'Tucson', 2016, 2020, 'MDPS Direksiyon Arızası',
     'Motor tahrikli direksiyon (MDPS) yazılım hatası nedeniyle direksiyon düzensiz '
     'ağırlaşabilir veya arıza ışığı yakabilir.',
     'direksiyon', 'medium', 40000),
    ('Hyundai', 'Elantra', 2016, 2020, 'Arka Tekerlek Yatağı Uğultusu',
     'Arka tekerlek yatakları 60.000-80.000 km\'de uğultu sesi çıkarmaya başlayabilir.',
     'sasi', 'medium', 70000),
    # ── Kia ──────────────────────────────────────────────────────────────────
    ('Kia', 'Sportage', 2016, 2021, 'Triger Zinciri Uzaması (Benzin)',
     'Benzinli modellerde triger zinciri erken uzayabilir; soğuk çalışmada metal ses duyulur. '
     'Yağ değişimine dikkat edilmeli.',
     'motor', 'high', 60000),
    ('Kia', 'Sportage', 2016, 2021, 'Dizel DPF Tıkanması',
     'Dizel modellerde kısa mesafe kullanımında DPF filtresi tıkanabilir. '
     'Düzenli uzun yolculuk yapılması önerilir.',
     'egzoz', 'medium', 50000),
    ('Kia', 'Ceed', 2012, 2018, 'Klima Gaz Kaçağı',
     'Klima sistemi bağlantılarından gaz kaçağı yaşanabilir; klima soğutma performansı düşer.',
     'klima', 'medium', 60000),
    ('Kia', 'Picanto', 2011, 2017, 'Şanzıman Konan Titreşimi',
     '5. viteste 120 km/s üzerinde titreşim hissedilebilir.',
     'sanziman', 'low', 50000),
    # ── Dacia ────────────────────────────────────────────────────────────────
    ('Dacia', 'Sandero', 2012, 2020, 'Ön Amortisör Sesi',
     'Ön amortisör üst tampon yatakları ve lastikleri erken aşınır; bozuk yolda tıkırtı çıkar.',
     'sasi', 'medium', 40000),
    ('Dacia', 'Duster', 2012, 2018, 'Arka Aks Yatağı Arızası (4WD)',
     '4WD modellerde arka aks yatağı öngörülenden erken aşınabilir.',
     'sasi', 'medium', 60000),
    ('Dacia', 'Logan', 2012, 2020, 'Kaporta Gürültüsü (Titreşim)',
     'Kapı ve bagaj kapağı keçeleri erken yorulur, yüksek hızda titreşim sesi çıkar.',
     'karoser', 'low', None),
    # ── Skoda ────────────────────────────────────────────────────────────────
    ('Skoda', 'Octavia', 2013, 2020, 'DSG Mekatronik Arızası',
     'DSG şanzımanın mekatronik ünitesi arızalanarak vites takılması veya arıza ışığı '
     'yakmaya neden olabilir.',
     'sanziman', 'high', 60000),
    ('Skoda', 'Octavia', 2013, 2020, 'Su Pompası Arızası (1.4 TSI)',
     'Plastik gövdeli su pompası erken çatlayabilir; motorun aşırı ısınmasına yol açar.',
     'sogutma', 'high', 80000),
    ('Skoda', 'Fabia', 2015, 2021, 'Güç Kaybı (1.0 MPI)',
     '1.0 MPI motorlarda EGR valfı kirlenmesi nedeniyle güç kaybı yaşanabilir.',
     'motor', 'medium', 70000),
    ('Skoda', 'Karoq', 2017, None, 'Isıtmalı Koltuk Sigortası',
     'Isıtmalı koltuk devresinin sigortası sık sık atabilerek oturmalı ısıtma çalışmayabilir.',
     'elektrik', 'low', None),
    # ── BMW ──────────────────────────────────────────────────────────────────
    ('BMW', '3 Serisi', 2012, 2018, 'Soğutma Sistemi Sızıntısı',
     'Plastik soğutma sistemi bileşenleri (genleşme deposu, hortumlar) zamanla çatlayabilir. '
     'Düzenli kontrol şarttır.',
     'sogutma', 'high', 80000),
    ('BMW', '3 Serisi', 2012, 2018, 'Yüksek Yağ Tüketimi (N20/N26)',
     'N20 ve N26 motorlarda piston halkaları aşınan vakaların yağ tüketimi normalin '
     '2-3 katına çıkabilir.',
     'motor', 'high', 60000),
    ('BMW', '5 Serisi', 2013, 2017, 'N47 Dizel Zinciri Uzaması',
     'N47 dizel motorlarda arka taraftaki triger zinciri ve gergi mekanizması erken '
     'aşınabilir. Motor ön taraftan sökülmesi gerektiği için maliyetli onarım gerekir.',
     'motor', 'critical', 100000),
    ('BMW', 'X1', 2016, None, 'Turbo Basınç Kaybı (B47)',
     'B47 dizel motorlarda turbo ara soğutucu hortumu zaman zaman yerinden çıkabilir.',
     'motor', 'medium', 70000),
    ('BMW', 'X3', 2017, None, 'Transfer Kutusu Sarsıntısı',
     'xDrive transfer kutusu soğukta sarsıntı yapabilir; yağ değişimi sorunun çözümüne '
     'yardımcı olabilir.',
     'sanziman', 'medium', 60000),
    # ── Mercedes-Benz ────────────────────────────────────────────────────────
    ('Mercedes-Benz', 'C Serisi', 2014, 2021, '7G-Tronic Vites Arızası',
     '7G-Tronic otomatik şanzımanın selenoid valfleri arızalanabilir; vites gecikmesi '
     've sert vites değişimi görülür.',
     'sanziman', 'medium', 100000),
    ('Mercedes-Benz', 'C Serisi', 2014, 2021, 'OM651 Dizel Yağ Tüketimi',
     'OM651 dizel motorlarda piston halkaları aşınması ile yağ tüketimi artabilir.',
     'motor', 'medium', 80000),
    ('Mercedes-Benz', 'A Serisi', 2013, 2018, 'DSG/DCT Titreşimi',
     '7G-DCT şanzımanda düşük hız ve marş anında titreşim görülmektedir.',
     'sanziman', 'medium', 40000),
    ('Mercedes-Benz', 'E Serisi', 2016, None, 'Aktif Direksiyon Arızası',
     'Aktif direksiyon sistemi sensörleri arızalanarak direksiyon ağırlaşabilir.',
     'direksiyon', 'medium', 80000),
    # ── Audi ─────────────────────────────────────────────────────────────────
    ('Audi', 'A3', 2013, 2020, 'S-Tronic Mekatronik Arızası',
     'S-Tronic DSG şanzımanın mekatronik ünitesi arızalanabilir; titreşim ve vites '
     'takılması görülür.',
     'sanziman', 'high', 60000),
    ('Audi', 'A3', 2013, 2020, 'Hava Süspansiyon Kompresörü (S3)',
     'S3 modellerinde hava süspansiyon kompresörü erken arızalanabilir.',
     'sasi', 'medium', 80000),
    ('Audi', 'A4', 2016, None, 'Yağ Filtresi Kapağı Sızıntısı',
     'Yağ filtresi kapağı contası zamanla sızıntı yapabilir; düzenli kontrol önerilir.',
     'motor', 'low', 60000),
    ('Audi', 'Q5', 2017, None, 'Quattro Transfer Kutusu Sarsıntısı',
     'Quattro sisteminde transfer kutusu soğukta sarsıntı yapabilir; yazılım güncellemesi '
     've Haldex yağı değişimi çözüm olabilir.',
     'sanziman', 'medium', 60000),
    # ── Peugeot ──────────────────────────────────────────────────────────────
    ('Peugeot', '308', 2014, 2021, 'EGR Valfı Tıkanması',
     'EGR valfı zamanla karbon birikimi nedeniyle tıkanır; güç kaybı ve arıza ışığı yanar.',
     'motor', 'medium', 80000),
    ('Peugeot', '308', 2014, 2021, 'Faz Değiştirici (VVT) Arızası',
     'Faz değiştirici mekanizması erken aşınabilir; soğuk çalışmada metal ses duyulur.',
     'motor', 'high', 100000),
    ('Peugeot', '2008', 2013, 2019, 'Ön Amortisör Zımba Sesi',
     'Ön amortisör üst yataklarındaki boşluk nedeniyle bozuk zeminde tıkırtı çıkar.',
     'sasi', 'low', 50000),
    ('Peugeot', '3008', 2016, None, 'e-HDi Durdurmaksızın Kalkış Problemi',
     'Start/Stop sistemi bazen motoru yanlış zamanda durdurabilir veya yeniden '
     'çalıştırmakta gecikebilir.',
     'elektrik', 'low', None),
    # ── Citroen ──────────────────────────────────────────────────────────────
    ('Citroen', 'C3', 2016, None, 'Arka Amortisör Sesi',
     'Arka amortisörler ve bağlantı elemanları erken aşınarak titreşim sesine neden olur.',
     'sasi', 'medium', 50000),
    ('Citroen', 'C5 Aircross', 2018, None, 'Ön Fren Diski Çarpıklığı',
     'Fren balata/disk kombinasyonu nedeniyle yüksek hızlarda frenleme titreşimi oluşabilir.',
     'fren', 'medium', 40000),
    # ── Fiat ─────────────────────────────────────────────────────────────────
    ('Fiat', 'Egea', 2015, None, 'Kaporta Gürültüsü',
     'Kapı keçeleri ve bagaj kapağı titreşim sesi kaynağı olabilir.',
     'karoser', 'low', None),
    ('Fiat', 'Egea', 2015, None, 'Şanzıman Gürültüsü (Manuel)',
     'Manuel şanzımanda geri viteste metalik ses duyulabilir.',
     'sanziman', 'low', 40000),
    ('Fiat', '500', 2012, None, 'Klima Kompresörü Arızası',
     'Klima kompresörü öngörülenden erken arızalanabilir.',
     'klima', 'medium', 60000),
    # ── Opel ─────────────────────────────────────────────────────────────────
    ('Opel', 'Astra', 2016, 2021, 'Şanzıman Salıncağı Lastiği Aşınması',
     'Şanzıman askı lastiği erken aşınarak vites değişiminde titreşim hissedilir.',
     'sanziman', 'low', 60000),
    ('Opel', 'Corsa', 2014, 2019, 'Ön Amortisör Sesi',
     'Ön amortisör üst yatakları hızla aşınarak bozuk zeminde tıkırtı çıkarır.',
     'sasi', 'low', 50000),
    ('Opel', 'Insignia', 2013, 2017, 'Dizel DPF Tıkanması',
     'Kısa mesafe sürüşlerde DPF tıkanması ve arıza ışığı yaygındır.',
     'egzoz', 'medium', 60000),
]

CHRONIC_CATEGORY_LABELS = {
    'motor': 'Motor',
    'sanziman': 'Şanzıman',
    'elektrik': 'Elektrik',
    'sogutma': 'Soğutma Sistemi',
    'fren': 'Fren Sistemi',
    'sasi': 'Şasi / Süspansiyon',
    'egzoz': 'Egzoz',
    'klima': 'Klima',
    'direksiyon': 'Direksiyon',
    'karoser': 'Kaporta / Karoser',
    'diger': 'Diğer',
}


def get_chronic_faults(brand, model, year):
    """Return list of known chronic faults matching brand/model/year."""
    results = []
    for fault in CHRONIC_FAULTS:
        f_brand, f_model, year_from, year_to = fault[0], fault[1], fault[2], fault[3]
        if f_brand.lower() != brand.lower():
            continue
        if f_model.lower() != model.lower():
            continue
        if year < year_from:
            continue
        if year_to is not None and year > year_to:
            continue
        results.append({
            'title': fault[4],
            'description': fault[5],
            'category': fault[6],
            'category_label': CHRONIC_CATEGORY_LABELS.get(fault[6], fault[6].title()),
            'severity': fault[7],
            'approx_km': fault[8],
        })
    return results


def seed(db_path=DATABASE):
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    cur.executescript('''
        CREATE TABLE IF NOT EXISTS vehicle_catalog (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            brand TEXT NOT NULL, model TEXT NOT NULL,
            year_from INTEGER NOT NULL, year_to INTEGER,
            fuel_type TEXT NOT NULL, category TEXT NOT NULL DEFAULT 'sedan'
        );
        CREATE TABLE IF NOT EXISTS maintenance_templates (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            fuel_type TEXT, maintenance_type TEXT NOT NULL, keywords TEXT NOT NULL,
            interval_km INTEGER, interval_months INTEGER,
            cost_min_tl INTEGER, cost_max_tl INTEGER,
            priority TEXT NOT NULL DEFAULT 'routine', notes TEXT
        );
        CREATE TABLE IF NOT EXISTS engine_variants (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            brand TEXT NOT NULL, model TEXT NOT NULL,
            engine TEXT NOT NULL, fuel_type TEXT NOT NULL
        );
    ''')

    count = cur.execute('SELECT COUNT(*) FROM vehicle_catalog').fetchone()[0]
    if count == 0:
        cur.executemany(
            'INSERT OR IGNORE INTO vehicle_catalog (brand,model,year_from,year_to,fuel_type,category) VALUES (?,?,?,?,?,?)',
            VEHICLE_CATALOG
        )
        cur.executemany(
            '''INSERT INTO maintenance_templates
               (fuel_type,maintenance_type,keywords,interval_km,interval_months,cost_min_tl,cost_max_tl,priority,notes)
               VALUES (?,?,?,?,?,?,?,?,?)''',
            MAINTENANCE_TEMPLATES
        )

    ev_count = cur.execute('SELECT COUNT(*) FROM engine_variants').fetchone()[0]
    if ev_count == 0:
        cur.executemany(
            'INSERT INTO engine_variants (brand,model,engine,fuel_type) VALUES (?,?,?,?)',
            ENGINE_VARIANTS
        )

    conn.commit()
    conn.close()


if __name__ == '__main__':
    seed()
    print('Seeded.')